# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(error_messages={'required': 'First name is required.'}, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(error_messages={'required': 'Last name is required.'}, max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(error_messages={'required': 'Email is required.', 'unique': 'This email has already been registered.'}, max_length=100, unique=True, verbose_name='Email')),
                ('birthday', models.DateField(error_messages={'required': 'Birthday is required.'}, verbose_name='Birthday')),
                ('random_number', models.IntegerField(error_messages={'required': 'This number is required.'}, verbose_name='Random Number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
